[[headers]]
  for = "/*"

  [headers.values]
    Content-Security-Policy-Report-Only = "Content-Security-Policy-Report-Only: default-src 'none'; form-action 'none'; frame-ancestors 'none'; report-uri REPORT_URI"
    Report-To = '{"group":"default","max_age":31536000,"endpoints":[{"url":"REPORTING_API_PLACEHOLDER"}],"include_subdomains":true}'
