[[headers]]
  for = "/*"

  [headers.values]
    # Content-Security-Policy-Report-Only = "default-src 'none'; form-action 'none'; frame-ancestors 'none'; report-uri https://REPORT_URI_SUBDOMAIN_PLACEHOLDER.report-uri.com/r/d/csp/wizard"
    Content-Security-Policy = "connect-src REACT_APP_API_HOST_PLACEHOLDER https://cognito-idp.eu-west-1.amazonaws.com https://AS_PLACEHOLDER https://in.hotjar.com wss://*.hotjar.com; frame-src https://www.youtube.com https://vars.hotjar.com; img-src 'self'; script-src 'self' https://*.hotjar.com 'REACT_APP_HOTJAR_INLINE_SETUP_SRI_PLACEHOLDER' 'sha256-GgRxrVOKNdB4LrRsVPDSbzvfdV4UqglmviH9GoBJ5jk='; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; object-src 'none'; report-to default"
    Report-To = '{"group":"default","max_age":31536000,"endpoints":[{"url":"https://REPORT_URI_SUBDOMAIN_PLACEHOLDER.report-uri.com/a/d/g"}],"include_subdomains":true}'
    NEL = '{"report_to":"default","max_age":31536000,"include_subdomains":true}'
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Xss-Protection = "1; mode=block; report=https://REPORT_URI_SUBDOMAIN_PLACEHOLDER.report-uri.com/r/d/xss/enforce"
